### ISSUE TITLE
Abstract Syntaxes

### ISSUE THREAD

**Issue by pigworker** [msp-strath/TypOS#1]
TypOS has a very simple raw syntax: pairs and atoms, bindings and variables, metavariable instantiations. We could just use raw terms for everything, but that offers considerable potential for subtle errors. I propose that we equip ourselves with the means to characterise sets of raw terms which are in some sense well formed. E.g., we might introduce the distinction between "checkable constructions" and "synthesizable computations". Thus equipped, we can say which sorts of thing go where in judgement forms.

What are syntaxes like? As a syntax designer, I should be able to
1. Name syntaxes, and recursively demand substructures of a given syntax.
2. Demand a pair whose head has one syntax and whose tail has another, depending on the head.
3. Demand the nil atom.
4. Demand a binder, specifying the syntax of the bound variable and the syntax of the term under the binder.
5. Demand one of a specific set of non-nil atoms.
6. Perform case analysis on a component of known syntax, in order to compute a syntax.

I thus have to say what patterns are like. Note the "Law of Explicit Discrimination": the only things we can tell apart are non-nil atoms.

We could go nuts and define something an awful lot like type theory.

Let's at least try to spend fewer bucks, as long as we get enough bang.

**Comment by pigworker** [comment]
Reviewing how this has worked out for us, I think the "Law of Explicit Discrimination" might be too strong. It's why we write `['Cons 'a ['Cons 'b ['Cons 'c ['Nil]]]]` instead of `['a 'b 'c]`. The latter requires us to tell the atom nil apart from cons cells (i.e., to detect the null pointer) rather than to tell atoms apart from each other.

We could allow a new Syntax construct, `['NilOrCons `*head* *tail*`]`, which accepts `[]` as well as `[`*a*`|`*d*`]` when *head* accepts *a* and *tail* accepts *d*. Hopefully, this will allow us to get rid of the "is it listy?" hack, and quite a few backticks. Shouldn't be a big stretch to implement, given the will to do so.

Now, the *real* question is whether we allow atoms other than `[]`. We could rejig the `'Tag` syntax to take two lists: atoms which stand alone, then atoms which pair with more stuff. Operationally, this is more like reserving a bit in a pointer than distinguishing the null pointer. I'm less keen, just now, but open to persuasion.

**Comment by fredrikNordvallForsberg** [comment]
We have now implemented all of the above, except that we call the proposed extension to `'Tag` instead `'EnumOrTag`.
