### ISSUE TITLE
`mangleActors` is creating thinnings of negative size in some situations

### ISSUE THREAD

**Issue by fredrikNordvallForsberg** [msp-strath/TypOS#3]
Sadly this line
[
**https://github.com/msp-strath/TypOS/blob/main/Src/Actor.hs#L125**
](https://github.com/msp-strath/TypOS/blob/c248c0f1e3a045d5b88bbb5d80284e4f5c4f5d24/Src/Actor.hs#L125)

is not doing the right thing in general: in our `stlctpp.act` example, we have `scopeEnv env = 1` and `sc = 3` when mangling the term before we send it, resulting in a thinning of size -2... What is fun is that versions of GHC < 9.0 silently truncates our use of `shiftL` to 0, whereas [newer GHC versions crashes with an `arithmetic overflow`](https://gitlab.haskell.org/ghc/ghc/-/issues/18619).

**Comment by gallais** [comment]
Can it produce anything *but* thinnings of a negative size?
We start from `goSbst env` (so `scopeEnv env` is `sc` initially) and only ever modify `env` by using `strengthenEnv` thus decreasing its size.

**Comment by pigworker** [comment]
Let's see if we can walk through slowly.

1. We're acting on a term which is top-level *closed* and whose metas are actor variables.
2. We're yielding a term which is open with respect to binders we're under, and whose metas are known unknowns.
3. The environment maps the former to the latter, with its scope being the number of binders we're under (and we weaken when we push under more binders, locally).
4. Actor variables bound in *patterns* will have local scope if they were under binders in the patterns. Those local scopes must be substituted when those actor variables are used in terms.
5. When we encounter a substitution in a actor term, its source scope is the bindings the actor variable was under in the pattern which bound it, and its target scope is the bindings it is under in its term.

**Comment by fredrikNordvallForsberg** [comment]
Closed by today's session, producing a4457053154360dd49bdf5d5844248984149812a . But we should really be better at managing the scope of actor variables in the parser...
