### ISSUE TITLE
Both Show and Pretty ?

### ISSUE THREAD

**Issue by JacquesCarette** [msp-strath/TypOS#56]
There are a number of types (like MachineStep in Options) that have both Show and Pretty instances. Is this on purpose?

**Comment by gallais** [comment]
Are you suggesting we should define `pretty = pretty . show`?

**Comment by JacquesCarette** [comment]
No. If the `show` really is supposed to be parseable, then it has a place. If it's just for debugging, I'd be tempted to do `show = pretty` !
